import * as cheerio from 'cheerio';
export type AuditIssue={severity:'high'|'medium'|'low';category:string;title:string;message:string;evidence:string;fix:string;urls:string[]};category:string;message:string;fix:string};
export type AuditResult={url:string;status:number;title:string;description:string;h1s:string[];wordCount:number;images:number;imagesMissingAlt:number;schemas:string[];internalLinks:number;externalLinks:number;score:number;issues:AuditIssue[]};status:number;title:string;description:string;h1s:string[];wordCount:number;images:number;imagesMissingAlt:number;schemas:string[];internalLinks:number;externalLinks:number;score:number;issues:AuditIssue[]};
export async function auditUrl(input:string):Promise<AuditResult>{
 const url=new URL(input); const r=await fetch(url,{redirect:'follow',signal:AbortSignal.timeout(15000),headers:{'user-agent':'SiteLensBot/0.4'}}); if(!r.ok) throw new Error(`Website returned HTTP ${r.status}`);
 const html=await r.text(),$=cheerio.load(html),title=$('title').first().text().trim(),description=$('meta[name="description"]').attr('content')?.trim()||'',h1s=$('h1').map((_,e)=>$(e).text().trim()).get().filter(Boolean);
 let imagesMissingAlt=0;$('img').each((_,e)=>{if(!($(e).attr('alt')||'').trim())imagesMissingAlt++});
 const schemas:string[]=[];$('script[type="application/ld+json"]').each((_,e)=>{try{const j=JSON.parse($(e).text());for(const x of (Array.isArray(j)?j:[j]))if(x?.['@type'])schemas.push(...(Array.isArray(x['@type'])?x['@type']:[x['@type']]))}catch{}});
 let internal=0,external=0;$('a[href]').each((_,e)=>{try{const u=new URL($(e).attr('href')||'',r.url);u.origin===url.origin?internal++:external++}catch{}});
 const issues:AuditIssue[]=[];if(!title)issues.push({severity:'high',category:'On-page',title:'Missing title tag',message:'Missing title tag',evidence:`No title detected on ${r.url}.`,fix:'Add a unique descriptive title.',urls:[r.url]});if(!h1s.length)issues.push({severity:'medium',category:'On-page',title:'Missing H1',message:'Missing H1',evidence:`No H1 detected on ${r.url}.`,fix:'Add one clear primary heading.',urls:[r.url]});if(!description)issues.push({severity:'medium',category:'On-page',title:'Missing meta description',message:'Missing meta description',evidence:`No meta description detected on ${r.url}.`,fix:'Add a useful page summary.',urls:[r.url]});if(imagesMissingAlt)issues.push({severity:'low',category:'Accessibility',title:'Images missing alt text',message:`${imagesMissingAlt} images are missing alt text`,evidence:`${imagesMissingAlt} images lack alt text on ${r.url}.`,fix:'Add meaningful alt text to informative images.',urls:[r.url]});if(!schemas.length)issues.push({severity:'low',category:'Structured data',title:'No JSON-LD schema detected',message:'No JSON-LD schema detected',evidence:`No JSON-LD schema detected on ${r.url}.`,fix:'Assess whether appropriate structured data should be added.',urls:[r.url]});
 const score=Math.max(0,100-(issues.reduce((n,x)=>n+(x.severity==='high'?20:x.severity==='medium'?10:5),0)));
 const body=$('body').text().replace(/\s+/g,' ').trim(); const wordCount=body?body.split(/\s+/).length:0; return {url:r.url,status:r.status,title,description,h1s,wordCount,images:$('img').length,imagesMissingAlt,schemas:[...new Set(schemas)],internalLinks:internal,externalLinks:external,score,issues};
}