import * as cheerio from 'cheerio';
export type AuditIssue={severity:'high'|'medium'|'low';category:string;message:string;fix:string};
export type AuditResult={url:string;status:number;title:string;description:string;h1s:string[];images:number;imagesMissingAlt:number;schemas:string[];internalLinks:number;externalLinks:number;score:number;issues:AuditIssue[]};
export async function auditUrl(input:string):Promise<AuditResult>{
 const url=new URL(input); const r=await fetch(url,{redirect:'follow',signal:AbortSignal.timeout(15000),headers:{'user-agent':'SiteLensBot/0.4'}}); if(!r.ok) throw new Error(`Website returned HTTP ${r.status}`);
 const html=await r.text(),$=cheerio.load(html),title=$('title').first().text().trim(),description=$('meta[name="description"]').attr('content')?.trim()||'',h1s=$('h1').map((_,e)=>$(e).text().trim()).get().filter(Boolean);
 let imagesMissingAlt=0;$('img').each((_,e)=>{if(!($(e).attr('alt')||'').trim())imagesMissingAlt++});
 const schemas:string[]=[];$('script[type="application/ld+json"]').each((_,e)=>{try{const j=JSON.parse($(e).text());for(const x of (Array.isArray(j)?j:[j]))if(x?.['@type'])schemas.push(...(Array.isArray(x['@type'])?x['@type']:[x['@type']]))}catch{}});
 let internal=0,external=0;$('a[href]').each((_,e)=>{try{const u=new URL($(e).attr('href')||'',r.url);u.origin===url.origin?internal++:external++}catch{}});
 const issues:AuditIssue[]=[];if(!title)issues.push({severity:'high',category:'On-page',message:'Missing title tag',fix:'Add a unique descriptive title.'});if(!h1s.length)issues.push({severity:'medium',category:'On-page',message:'Missing H1',fix:'Add one clear primary heading.'});if(!description)issues.push({severity:'medium',category:'On-page',message:'Missing meta description',fix:'Add a useful page summary.'});if(imagesMissingAlt)issues.push({severity:'low',category:'Accessibility',message:`${imagesMissingAlt} images are missing alt text`,fix:'Add meaningful alt text to informative images.'});if(!schemas.length)issues.push({severity:'low',category:'Structured data',message:'No JSON-LD schema detected',fix:'Assess whether appropriate structured data should be added.'});
 const score=Math.max(0,100-(issues.reduce((n,x)=>n+(x.severity==='high'?20:x.severity==='medium'?10:5),0)));
 return {url:r.url,status:r.status,title,description,h1s,images:$('img').length,imagesMissingAlt,schemas:[...new Set(schemas)],internalLinks:internal,externalLinks:external,score,issues};
}