import * as cheerio from 'cheerio';
export type PageAudit={url:string;status:number;title:string;h1s:string[];description:string;canonical:string|null;wordCount:number;internalLinks:string[];externalLinks:string[];images:number;imagesMissingAlt:number;schemas:string[];depth:number;indexable:boolean;error?:string};
export type Finding={severity:'high'|'medium'|'low';category:string;title:string;evidence:string;fix:string;urls:string[]};
const norm=(s:string)=>{const u=new URL(s);u.hash='';if(u.pathname!=='/'&&u.pathname.endsWith('/'))u.pathname=u.pathname.slice(0,-1);return u.toString()};
export async function crawlSite(input:string,maxPages=30){const start=norm(input),origin=new URL(start).origin;let robots='',robotsFound=false,sitemapFound=false,sitemapUrls:string[]=[];try{const r=await fetch(origin+'/robots.txt',{signal:AbortSignal.timeout(8000),headers:{'user-agent':'SiteLensBot/0.4'}});robotsFound=r.ok;if(r.ok)robots=await r.text()}catch{};try{const r=await fetch(origin+'/sitemap.xml',{signal:AbortSignal.timeout(8000),headers:{'user-agent':'SiteLensBot/0.4'}});if(r.ok){const $=cheerio.load(await r.text(),{xmlMode:true});sitemapUrls=$('url loc').map((_,e)=>$(e).text().trim()).get().filter(Boolean).map(x=>{try{return norm(x)}catch{return x}});sitemapFound=sitemapUrls.length>0}}catch{};
 const q: Array<[string, number]> = [[start, 0], ...sitemapUrls.filter(x=>{try{return new URL(x).origin===origin}catch{return false}}).slice(0,maxPages-1).map((x): [string, number] => [x, 1])];const seen=new Set<string>(),pages:PageAudit[]=[];
 while(q.length&&pages.length<maxPages){const [url,depth]=q.shift()!;if(seen.has(url))continue;seen.add(url);try{const r=await fetch(url,{redirect:'follow',signal:AbortSignal.timeout(10000),headers:{'user-agent':'SiteLensBot/0.4'}});const type=r.headers.get('content-type')||'';if(!type.includes('text/html'))continue;const final=norm(r.url),$=cheerio.load(await r.text()),title=$('title').first().text().trim(),description=$('meta[name="description"]').attr('content')?.trim()||'',h1s=$('h1').map((_,e)=>$(e).text().trim()).get().filter(Boolean),internal:string[]=[],external:string[]=[];$('a[href]').each((_,e)=>{try{const u=norm(new URL($(e).attr('href')||'',final).toString());new URL(u).origin===origin?(internal.push(u),depth<4&&!seen.has(u)&&q.push([u,depth+1])):external.push(u)}catch{}});let alt=0;$('img').each((_,e)=>{if(!($(e).attr('alt')||'').trim())alt++});const schemas:string[]=[];$('script[type="application/ld+json"]').each((_,e)=>{try{const j=JSON.parse($(e).text());for(const x of (Array.isArray(j)?j:[j]))if(x?.['@type'])schemas.push(...(Array.isArray(x['@type'])?x['@type']:[x['@type']]))}catch{}});const body=$('body').text().replace(/\s+/g,' ').trim();const robotsMeta=($('meta[name="robots"]').attr('content')||'').toLowerCase();pages.push({url,status:r.status,title,h1s,description,canonical:$('link[rel="canonical"]').attr('href')||null,wordCount:body?body.split(/\s+/).length:0,internalLinks:[...new Set(internal)],externalLinks:[...new Set(external)],images:$('img').length,imagesMissingAlt:alt,schemas:[...new Set(schemas)],depth,indexable:!robotsMeta.includes('noindex')})}catch(e){pages.push({url,status:0,title:'',h1s:[],description:'',canonical:null,wordCount:0,internalLinks:[],externalLinks:[],images:0,imagesMissingAlt:0,schemas:[],depth,indexable:false,error:e instanceof Error?e.message:'Request failed'})}};
 const findings:Finding[]=[];const titles=new Map<string,string[]>(),descs=new Map<string,string[]>();for(const p of pages){if(p.status>=400||p.status===0)findings.push({severity:'high',category:'Crawl',title:`Page returns ${p.status||'an error'}`,evidence:`${p.url} returned HTTP ${p.status||'no response'}.`,fix:'Repair or redirect the URL.',urls:[p.url]});if(!p.title)findings.push({severity:'high',category:'On-page',title:'Missing title tag',evidence:`No title detected on ${p.url}.`,fix:'Add a unique descriptive title.',urls:[p.url]});else titles.set(p.title,[...(titles.get(p.title)||[]),p.url]);if(!p.h1s.length)findings.push({severity:'medium',category:'On-page',title:'Missing H1',evidence:`No H1 detected on ${p.url}.`,fix:'Add one clear primary heading.',urls:[p.url]});if(!p.description)findings.push({severity:'medium',category:'On-page',title:'Missing meta description',evidence:`No meta description detected on ${p.url}.`,fix:'Add a useful summary.',urls:[p.url]});else descs.set(p.description,[...(descs.get(p.description)||[]),p.url]);if(!p.indexable)findings.push({severity:'medium',category:'Indexability',title:'Page is not indexable',evidence:`A noindex directive was detected on ${p.url}.`,fix:'Remove noindex if the page should rank.',urls:[p.url]});if(p.imagesMissingAlt)findings.push({severity:'low',category:'Accessibility',title:'Images missing alt text',evidence:`${p.imagesMissingAlt} images lack alt text.`,fix:'Add meaningful alt text to informative images.',urls:[p.url]});if(p.wordCount<200)findings.push({severity:'low',category:'Content',title:'Low visible word count',evidence:`${p.wordCount} visible words detected.`,fix:'Confirm the page satisfies its intent.',urls:[p.url]})}
 for(const [t,urls] of titles)if(urls.length>1)findings.push({severity:'medium',category:'Content',title:'Duplicate title tags',evidence:`The same title appears on ${urls.length} pages.`,fix:'Make titles unique.',urls});for(const [d,urls] of descs)if(urls.length>1)findings.push({severity:'low',category:'Content',title:'Duplicate meta descriptions',evidence:`The same description appears on ${urls.length} pages.`,fix:'Differentiate descriptions where useful.',urls});
 const stats={pagesCrawled:pages.length,errors:pages.filter(p=>p.status>=400||p.status===0).length,notIndexable:pages.filter(p=>!p.indexable).length,missingTitles:pages.filter(p=>!p.title).length,missingH1:pages.filter(p=>!p.h1s.length).length,missingDescriptions:pages.filter(p=>!p.description).length};
 return {pages,sitemapFound,robotsFound,sitemapUrls,findings,stats};
}