'use client';
import {useEffect,useMemo,useState} from 'react';
import type {AuditResult} from '@/lib/audit';

type Page={url:string;status:number;finalUrl?:string;title:string;h1s:string[];description:string;canonical:string|null;robotsDirective:string;wordCount:number;internalLinks:string[];externalLinks:string[];images:number;imagesMissingAlt:number;schemas:string[];schemaValid:boolean;depth:number;titleLength:number;descriptionLength:number;indexable:boolean;contentHash:string;error?:string};
type Finding={severity:'high'|'medium'|'low';category:string;title:string;evidence:string;fix:string;urls:string[]};
type Crawl={pages:Page[];sitemapFound:boolean;robotsFound:boolean;sitemapUrls:string[];findings:Finding[];stats:Record<string,number>};
type HistoryItem={url:string;hostname:string;score:number;issues:number;timestamp:string;title:string;pages?:number;high?:number;medium?:number;low?:number;findingTitles?:string[]};
const KEY='sitelens:audit-history:v1';
function readHistory():HistoryItem[]{try{return JSON.parse(localStorage.getItem(KEY)||'[]')}catch{return[]}}
function saveHistory(item:HistoryItem){const next=[item,...readHistory().filter(x=>!(x.url===item.url&&Date.now()-new Date(x.timestamp).getTime()<2000))].slice(0,50);localStorage.setItem(KEY,JSON.stringify(next));return next}

export default function Dashboard(){
 const [data,setData]=useState<AuditResult|null>(null),[crawl,setCrawl]=useState<Crawl|null>(null),[loading,setLoading]=useState(true),[crawling,setCrawling]=useState(false),[error,setError]=useState(''),[elapsed,setElapsed]=useState(0),[crawlElapsed,setCrawlElapsed]=useState(0),[history,setHistory]=useState<HistoryItem[]>([]),[saved,setSaved]=useState(false);
 const params=typeof window!=='undefined'?new URLSearchParams(window.location.search):null;const url=params?.get('url')||'';
 useEffect(()=>{setHistory(readHistory());if(!url){setLoading(false);return}let active=true;const start=Date.now();const tick=setInterval(()=>setElapsed(Math.floor((Date.now()-start)/1000)),500);const controller=new AbortController();const timer=setTimeout(()=>controller.abort(),30000);fetch('/api/audit',{method:'POST',headers:{'content-type':'application/json'},body:JSON.stringify({url}),signal:controller.signal}).then(async r=>{const x=await r.json();if(!r.ok||x.error)throw new Error(x.error||'Audit failed');if(active){setData(x);const item={url:x.url,hostname:new URL(x.url).hostname,score:x.score,issues:x.issues.length,timestamp:new Date().toISOString(),title:x.title};setHistory(saveHistory(item));}}).catch(e=>{if(active)setError(e.name==='AbortError'?'The audit exceeded 30 seconds. The website may be slow or blocking automated requests.':'Unable to complete the audit: '+e.message)}).finally(()=>{clearTimeout(timer);clearInterval(tick);if(active)setLoading(false)});return()=>{active=false;controller.abort();clearTimeout(timer);clearInterval(tick)}},[url]);
 useEffect(()=>{if(!crawling)return;const start=Date.now();const t=setInterval(()=>setCrawlElapsed(Math.floor((Date.now()-start)/1000)),500);return()=>clearInterval(t)},[crawling]);
 const runCrawl=()=>{setError('');setCrawling(true);setCrawlElapsed(0);fetch('/api/crawl',{method:'POST',headers:{'content-type':'application/json'},body:JSON.stringify({url,maxPages:30})}).then(async r=>{const x=await r.json();if(!r.ok||x.error)throw new Error(x.error);setCrawl(x);const item={url,hostname:new URL(url).hostname,score:data?.score||0,issues:data?.issues.length||0,timestamp:new Date().toISOString(),title:data?.title||'',pages:x.stats.pagesCrawled,high:x.findings.filter((f:Finding)=>f.severity==='high').length,medium:x.findings.filter((f:Finding)=>f.severity==='medium').length,low:x.findings.filter((f:Finding)=>f.severity==='low').length,findingTitles:x.findings.map((f:Finding)=>f.title)};setHistory(saveHistory(item));}).catch(e=>setError(e.message)).finally(()=>setCrawling(false))};
 const saveReport=()=>{if(!data)return;const report={generatedAt:new Date().toISOString(),audit:data,crawl};const blob=new Blob([JSON.stringify(report,null,2)],{type:'application/json'});const a=document.createElement('a');a.href=URL.createObjectURL(blob);a.download=`sitelens-${new URL(data.url).hostname}-${new Date().toISOString().slice(0,10)}.json`;a.click();URL.revokeObjectURL(a.href);setSaved(true);setTimeout(()=>setSaved(false),2500)};
 const prior=useMemo(()=>{if(!data)return null;const h=readHistory().filter(x=>x.hostname===new URL(data.url).hostname&&x.url===data.url);return h.length>1?h[1]:null},[data]);
 if(loading)return <Shell><AuditLoading elapsed={elapsed} url={url}/></Shell>;
 if(error&&!data)return <Shell><div className="py-16"><h1 className="text-3xl font-bold">Audit couldn't complete</h1><p className="muted mt-3 max-w-xl">{error}</p><div className="flex flex-wrap gap-3 mt-6"><button className="btn btn-primary" onClick={()=>location.reload()}>Try again</button><a className="btn btn-secondary" href="/">Audit another site</a></div></div></Shell>;if(!data)return <Shell><p className="muted">No URL was provided.</p></Shell>;
 const high=crawl?.findings.filter(x=>x.severity==='high').length||0,med=crawl?.findings.filter(x=>x.severity==='medium').length||0,low=crawl?.findings.filter(x=>x.severity==='low').length||0;
 return <Shell>
  <header className="flex flex-wrap items-center justify-between gap-4"><div><div className="accent text-xs font-bold tracking-[.25em]">AUDIT REPORT</div><button onClick={()=>location.href='/'} className="text-left text-4xl sm:text-5xl font-black mt-2 break-words hover:opacity-80" title="Back to home">{new URL(data.url).hostname}</button><p className="muted mt-2">{data.title||'No title detected'}</p></div><div className="flex flex-wrap gap-2"><a className="btn btn-secondary" href="/">New audit</a><button className="btn btn-secondary" onClick={saveReport}>{saved?'Report saved':'Save report'}</button><button className="btn btn-primary" onClick={runCrawl} disabled={crawling}>{crawling?'Crawling…':'Run full SEO crawl'}</button></div></header>
  {error&&<div className="card p-4 mt-5 border-[#8a5555]">{error}</div>}
  <div className="grid lg:grid-cols-[180px_1fr] gap-6 mt-8"><div className="card p-5 flex lg:flex-col items-center justify-center gap-4"><div className="score-ring" style={{'--score':`${data.score}%`} as React.CSSProperties}><div>{data.score}</div></div><div className="text-center"><div className="font-bold">Technical SEO</div><div className="muted text-xs mt-1">Initial page score</div></div></div><div className="grid sm:grid-cols-2 lg:grid-cols-4 gap-4"><Metric label="H1" value={data.h1s.length?`${data.h1s.length} detected`:'Missing'} bad={!data.h1s.length}/><Metric label="Meta description" value={data.description?'Present':'Missing'} bad={!data.description}/><Metric label="Schema" value={data.schemas.length?data.schemas.slice(0,2).join(', '):'Not detected'} bad={!data.schemas.length}/><Metric label="Images / alt gaps" value={`${data.images} / ${data.imagesMissingAlt}`} bad={data.imagesMissingAlt>0}/></div></div>
  {prior&&<section className="card p-5 mt-6"><div className="muted text-xs font-bold tracking-[.2em]">HISTORICAL CHANGE</div><div className="grid sm:grid-cols-3 gap-4 mt-3"><Delta label="SEO score" now={data.score} old={prior.score}/><Delta label="Page issues" now={data.issues.length} old={prior.issues} inverse/></div><p className="muted text-xs mt-4">Compared with the previous saved audit for this URL.</p></section>}
  {crawl&&<><section className="mt-8 grid sm:grid-cols-2 lg:grid-cols-4 gap-4"><Stat label="Pages crawled" value={crawl.stats.pagesCrawled}/><Stat label="Errors" value={crawl.stats.errors} bad={crawl.stats.errors>0}/><Stat label="Not indexable" value={crawl.stats.notIndexable} bad={crawl.stats.notIndexable>0}/><Stat label="Missing titles" value={crawl.stats.missingTitles} bad={crawl.stats.missingTitles>0}/></section><section className="mt-6 grid lg:grid-cols-3 gap-4"><Priority label="HIGH PRIORITY" value={high} text="Crawl or indexability risks"/><Priority label="MEDIUM" value={med} text="Structural and content issues"/><Priority label="LOW / OPTIMIZE" value={low} text="Quality and optimization opportunities"/></section>
  <section className="mt-8 card p-6"><div className="flex flex-wrap items-center justify-between gap-3"><div><h2 className="text-xl font-bold">SEO intelligence findings</h2><p className="muted text-sm mt-1">Every finding is generated from crawl evidence.</p></div><span className="pill">{crawl.findings.length} findings</span></div><div className="mt-5 space-y-3">{crawl.findings.length===0?<div className="p-4 rounded-xl bg-[#20201f]">No issues detected by the current rules.</div>:crawl.findings.map((i,n)=><div key={n} className="rounded-xl border border-[#353133] p-4"><div className="flex flex-wrap gap-2 items-center"><span className="pill" style={{color:i.severity==='high'?'#ed7777':i.severity==='medium'?'#e7bd6c':'#8bbbd3'}}>{i.severity.toUpperCase()}</span><span className="pill">{i.category}</span><strong>{i.title}</strong></div><p className="muted text-sm mt-2"><b>Evidence:</b> {i.evidence}</p><p className="text-sm mt-2"><b>Fix:</b> {i.fix}</p>{i.urls.length>0&&<p className="muted text-xs mt-2 truncate">Affected: {i.urls.join(' · ')}</p>}</div>)}</div></section>
  <section className="mt-8 card p-6"><div className="flex flex-wrap items-center justify-between gap-3"><div><h2 className="text-xl font-bold">Crawl health</h2><p className="muted text-sm mt-1">{crawl.pages.length} pages · Robots.txt {crawl.robotsFound?'found':'not found'} · Sitemap {crawl.sitemapFound?'found':'not found'} · {crawl.sitemapUrls.length} sitemap URLs</p></div><span className="pill">Depth-aware</span></div><div className="overflow-x-auto mt-5"><table className="w-full text-sm"><thead><tr className="text-left muted border-b border-[#353133]"><th className="py-3 pr-4">Page</th><th className="py-3 pr-4">Status</th><th className="py-3 pr-4">Index</th><th className="py-3 pr-4">Title</th><th className="py-3 pr-4">H1</th><th className="py-3 pr-4">Words</th><th className="py-3 pr-4">Depth</th><th className="py-3">Issues</th></tr></thead><tbody>{crawl.pages.map((p,i)=>{const issues=(p.title?0:1)+(p.h1s.length?0:1)+(p.description?0:1)+(p.imagesMissingAlt?1:0)+(p.indexable?0:1)+(p.status>=400||p.status===0?1:0);return <tr key={i} className="border-b border-[#2b2829]"><td className="py-3 pr-4 max-w-[280px] truncate" title={p.url}>{p.url}</td><td className="py-3 pr-4">{p.status||'ERR'}</td><td className="py-3 pr-4">{p.indexable?'Yes':'No'}</td><td className="py-3 pr-4 max-w-[220px] truncate">{p.title||'Missing'}</td><td className="py-3 pr-4">{p.h1s.length}</td><td className="py-3 pr-4">{p.wordCount}</td><td className="py-3 pr-4">{p.depth}</td><td className="py-3">{issues?<span className="text-[#e7bd6c]">{issues}</span>:<span className="text-[#6dd3a0]">0</span>}</td></tr>})}</tbody></table></div></section></>}
  {crawling&&<CrawlLoading elapsed={crawlElapsed}/>} {!crawl&&<section className="mt-8 card p-6"><h2 className="text-xl font-bold">SEO intelligence</h2><p className="muted mt-2">Run the full crawl to analyze indexability, duplicate metadata, content depth, internal architecture, schema, and crawl health.</p></section>}
  <section className="mt-8 grid md:grid-cols-2 gap-4"><div className="card p-6"><h2 className="font-bold">AEO / GEO</h2><p className="muted text-sm mt-2">Question coverage, entity clarity, citation readiness and AI visibility come next.</p></div><div className="card p-6"><h2 className="font-bold">Social & Brand</h2><p className="muted text-sm mt-2">Profile consistency, activity and content opportunities follow the SEO foundation.</p></div></section>
  <HistoryPanel hostname={new URL(data.url).hostname} history={history}/>
 </Shell>
}
function AuditLoading({elapsed,url}:{elapsed:number;url:string}){const pct=Math.min(96,Math.round((elapsed/15)*100));const phase=elapsed<4?'Connecting to website…':elapsed<8?'Fetching page and metadata…':elapsed<12?'Analyzing headings, links and images…':'Finalizing SEO checks…';return <div className="py-20 max-w-2xl"><div className="accent text-xs font-bold tracking-[.25em]">LIVE AUDIT</div><h1 className="text-4xl font-black mt-3">Auditing {url}…</h1><p className="muted mt-3">{phase}</p><div className="card p-5 mt-8"><div className="flex justify-between text-sm"><span>Expected result time</span><strong>{elapsed<15?'~5–15 seconds':'Taking longer than expected'}</strong></div><div className="h-2 bg-[#302c2e] rounded-full mt-4 overflow-hidden"><div className="h-full bg-[#d879c0] transition-all" style={{width:`${pct}%`}}/></div><div className="flex justify-between muted text-xs mt-3"><span>Elapsed {elapsed}s</span><span>{elapsed<30?'Timeout at 30s':'Timeout reached'}</span></div>{elapsed>=15&&<div className="mt-4 text-sm">The site is responding more slowly than normal. We will keep trying until the 30-second timeout, then show a retry option instead of leaving the page stuck.</div>}</div></div>}
function CrawlLoading({elapsed}:{elapsed:number}){return <div className="card p-5 mt-6"><div className="flex justify-between"><div><strong>Full crawl in progress</strong><p className="muted text-sm mt-1">Up to 30 pages, robots.txt, sitemap and page-level SEO checks.</p></div><span className="pill">{elapsed}s</span></div><div className="h-2 bg-[#302c2e] rounded-full mt-4 overflow-hidden"><div className="h-full bg-[#d879c0] animate-pulse" style={{width:'70%'}}/></div><p className="muted text-xs mt-2">Typical target: 30–120 seconds depending on the site and response speed.</p></div>}
function HistoryPanel({hostname,history}:{hostname:string;history:HistoryItem[]}){const rows=history.filter(h=>h.hostname===hostname).slice(0,10);return <section className="mt-8 card p-6"><div className="flex justify-between gap-3"><div><h2 className="text-xl font-bold">Audit history</h2><p className="muted text-sm mt-1">Previous checks for {hostname} saved in this browser.</p></div><span className="pill">{rows.length} saved</span></div>{rows.length===0?<p className="muted text-sm mt-5">Save an audit to start building your history.</p>:<div className="overflow-x-auto mt-5"><table className="w-full text-sm"><thead><tr className="text-left muted border-b border-[#353133]"><th className="py-3 pr-4">Date</th><th className="py-3 pr-4">SEO</th><th className="py-3 pr-4">Issues</th><th className="py-3">Pages</th></tr></thead><tbody>{rows.map((h,i)=><tr key={i} className="border-b border-[#2b2829]"><td className="py-3 pr-4">{new Date(h.timestamp).toLocaleString()}</td><td className="py-3 pr-4">{h.score}</td><td className="py-3 pr-4">{h.issues}</td><td className="py-3">{h.pages??'—'}</td></tr>)}</tbody></table></div>}</section>}
function Shell({children}:{children:React.ReactNode}){return <main className="min-h-screen grid-bg"><div className="max-w-6xl mx-auto px-6 py-8"><div className="flex items-center justify-between"><button onClick={()=>location.href='/'} className="font-black text-xl">Site<span className="accent">Lens</span></button><span className="pill">Evidence-based MVP</span></div>{children}</div></main>}
function Metric({label,value,bad}:{label:string,value:string,bad?:boolean}){return <div className="card p-5"><div className="muted text-xs">{label}</div><div className="font-bold mt-2" style={{color:bad?'#ed7777':'#f4f1f2'}}>{value}</div></div>}
function Stat({label,value,bad}:{label:string,value:number,bad?:boolean}){return <div className="card p-5"><div className="muted text-xs">{label}</div><div className="font-black text-3xl mt-2" style={{color:bad?'#ed7777':'#f4f1f2'}}>{value}</div></div>}
function Priority({label,value,text}:{label:string,value:number,text:string}){return <div className="card p-5"><div className="muted text-xs">{label}</div><div className="text-3xl font-black mt-2">{value}</div><div className="muted text-sm mt-1">{text}</div></div>}
function Delta({label,now,old,inverse=false}:{label:string,now:number,old:number,inverse?:boolean}){const d=now-old;const good=inverse?d<=0:d>=0;return <div><div className="muted text-xs">{label}</div><div className="font-bold mt-1">{now} <span style={{color:good?'#6dd3a0':'#ed7777'}}>{d===0?'—':d>0?`↑ ${d}`:`↓ ${Math.abs(d)}`}</span></div></div>}
