'use client';
import {useEffect,useState} from 'react';
import type {AuditResult} from '@/lib/audit';

type Crawl={pages:{url:string;status:number;title:string;h1s:string[];description:string;canonical:string|null;wordCount:number;internalLinks:string[];externalLinks:string[];images:number;imagesMissingAlt:number;schemas:string[];depth:number;error?:string}[];sitemapFound:boolean;robotsFound:boolean;sitemapUrls:string[]};
export default function Dashboard(){
 const [data,setData]=useState<AuditResult|null>(null),[crawl,setCrawl]=useState<Crawl|null>(null),[loading,setLoading]=useState(true),[crawling,setCrawling]=useState(false),[error,setError]=useState('');
 const params=typeof window!=='undefined'?new URLSearchParams(window.location.search):null;const url=params?.get('url')||'';
 useEffect(()=>{if(!url)return;fetch('/api/audit',{method:'POST',headers:{'content-type':'application/json'},body:JSON.stringify({url})}).then(r=>r.json()).then(x=>{if(x.error)throw new Error(x.error);setData(x)}).catch(e=>setError(e.message)).finally(()=>setLoading(false))},[url]);
 const runCrawl=()=>{setCrawling(true);fetch('/api/crawl',{method:'POST',headers:{'content-type':'application/json'},body:JSON.stringify({url,maxPages:30})}).then(r=>r.json()).then(x=>{if(x.error)throw new Error(x.error);setCrawl(x)}).catch(e=>setError(e.message)).finally(()=>setCrawling(false))};
 if(loading)return <Shell><div className="py-24"><div className="accent text-xs font-bold tracking-[.25em]">LIVE AUDIT</div><h1 className="text-4xl font-black mt-3">Crawling {url}…</h1><p className="muted mt-3">Collecting page evidence and calculating the technical score.</p></div></Shell>;
 if(error)return <Shell><h1 className="text-3xl font-bold">Audit failed</h1><p className="muted mt-3">{error}</p></Shell>;if(!data)return null;
 return <Shell><div className="flex flex-wrap items-center justify-between gap-3"><div><div className="accent text-xs font-bold tracking-[.25em]">AUDIT REPORT</div><h1 className="text-4xl sm:text-5xl font-black mt-2 break-words">{new URL(data.url).hostname}</h1><p className="muted mt-2">{data.title||'No title detected'}</p></div><button className="btn btn-primary" onClick={runCrawl} disabled={crawling}>{crawling?'Crawling…':'Crawl up to 30 pages'}</button></div>
 <div className="grid lg:grid-cols-[180px_1fr] gap-6 mt-8"><div className="card p-5 flex lg:flex-col items-center justify-center gap-4"><div className="score-ring" style={{'--score':`${data.score}%`} as React.CSSProperties}><div>{data.score}</div></div><div className="text-center"><div className="font-bold">Technical SEO</div><div className="muted text-xs mt-1">Measured from page evidence</div></div></div><div className="grid sm:grid-cols-2 lg:grid-cols-4 gap-4"><Metric label="H1" value={data.h1s.length?`${data.h1s.length} detected`:'Missing'} bad={!data.h1s.length}/><Metric label="Meta description" value={data.description?'Present':'Missing'} bad={!data.description}/><Metric label="Schema" value={data.schemas.length?data.schemas.slice(0,2).join(', '):'Not detected'} bad={!data.schemas.length}/><Metric label="Images / alt gaps" value={`${data.images} / ${data.imagesMissingAlt}`} bad={data.imagesMissingAlt>0}/></div></div>
 <section className="mt-8 grid lg:grid-cols-[1fr_320px] gap-6"><div className="card p-6"><div className="flex items-center justify-between"><h2 className="text-xl font-bold">Findings</h2><span className="pill">{data.issues.length} issues</span></div><div className="mt-5 space-y-3">{data.issues.length===0?<div className="p-4 rounded-xl bg-[#20201f]">No issues detected by the current rules.</div>:data.issues.map((i,n)=><div key={n} className="rounded-xl border border-[#353133] p-4"><div className="flex flex-wrap gap-2 items-center"><span className="pill" style={{color:i.severity==='high'?'#ed7777':i.severity==='medium'?'#e7bd6c':'#8bbbd3'}}>{i.severity.toUpperCase()}</span><strong>{i.title}</strong></div><p className="muted text-sm mt-2"><b>Evidence:</b> {i.evidence}</p><p className="text-sm mt-2"><b>Fix:</b> {i.fix}</p></div>)}</div></div><aside className="space-y-4"><div className="card p-6"><h2 className="font-bold">AEO / GEO</h2><p className="muted text-sm mt-2">Question coverage, entity clarity, citation readiness and AI visibility are next.</p></div><div className="card p-6"><h2 className="font-bold">Social & Brand</h2><p className="muted text-sm mt-2">Profile consistency, activity and content opportunities will follow the crawl engine.</p></div></aside></section>
 {crawl&&<section className="mt-8 card p-6"><div className="flex flex-wrap items-center justify-between gap-3"><div><h2 className="text-xl font-bold">Site crawl</h2><p className="muted text-sm mt-1">{crawl.pages.length} pages checked · Robots.txt {crawl.robotsFound?'found':'not found'} · Sitemap {crawl.sitemapFound?'found':'not found'}</p></div><span className="pill">Depth-aware crawl</span></div><div className="overflow-x-auto mt-5"><table className="w-full text-sm"><thead><tr className="text-left muted border-b border-[#353133]"><th className="py-3 pr-4">Page</th><th className="py-3 pr-4">Status</th><th className="py-3 pr-4">Title</th><th className="py-3 pr-4">H1</th><th className="py-3 pr-4">Words</th><th className="py-3">Issues</th></tr></thead><tbody>{crawl.pages.map((p,i)=>{const issues=(p.title?'':1)+(p.h1s.length?0:1)+(p.description?0:1)+(p.imagesMissingAlt?1:0);return <tr key={i} className="border-b border-[#2b2829]"><td className="py-3 pr-4 max-w-[280px] truncate" title={p.url}>{p.url}</td><td className="py-3 pr-4">{p.status||'ERR'}</td><td className="py-3 pr-4 max-w-[220px] truncate">{p.title||'Missing'}</td><td className="py-3 pr-4">{p.h1s.length}</td><td className="py-3 pr-4">{p.wordCount}</td><td className="py-3">{issues? <span className="text-[#e7bd6c]">{issues}</span>:<span className="text-[#6dd3a0]">0</span>}</td></tr>})}</tbody></table></div></section>}
 </Shell>}
function Shell({children}:{children:React.ReactNode}){return <main className="min-h-screen grid-bg"><div className="max-w-6xl mx-auto px-6 py-8"><div className="flex items-center justify-between"><div className="font-black text-xl">Site<span className="accent">Lens</span></div><span className="pill">Evidence-based MVP</span></div>{children}</div></main>}
function Metric({label,value,bad}:{label:string,value:string,bad?:boolean}){return <div className="card p-5"><div className="muted text-xs">{label}</div><div className="font-bold mt-2" style={{color:bad?'#ed7777':'#f4f1f2'}}>{value}</div></div>}
