'use client';
import {useEffect,useMemo,useState} from 'react';import type {AuditResult} from '@/lib/audit';
type P={url:string;status:number;title:string;h1s:string[];description:string;canonical:string|null;wordCount:number;internalLinks:string[];externalLinks:string[];images:number;imagesMissingAlt:number;schemas:string[];depth:number;indexable:boolean;error?:string};type F={severity:'high'|'medium'|'low';category:string;title:string;evidence:string;fix:string;urls:string[]};type C={pages:P[];sitemapFound:boolean;robotsFound:boolean;sitemapUrls:string[];findings:F[];stats:Record<string,number>};type H={url:string;hostname:string;score:number;issues:number;timestamp:string;title:string;pages?:number};const KEY='sitelens:audit-history:v1';
function history(){try{return JSON.parse(localStorage.getItem(KEY)||'[]')}catch{return[]}}function save(x:H){const a=[x,...history()].slice(0,50);localStorage.setItem(KEY,JSON.stringify(a));return a}
export default function Dashboard(){const params=typeof window!=='undefined'?new URLSearchParams(location.search):null,url=params?.get('url')||'';const[data,setData]=useState<AuditResult|null>(null),[crawl,setCrawl]=useState<C|null>(null),[loading,setLoading]=useState(true),[error,setError]=useState(''),[elapsed,setElapsed]=useState(0),[crawling,setCrawling]=useState(false),[crawlElapsed,setCrawlElapsed]=useState(0),[saved,setSaved]=useState(false);
useEffect(()=>{if(!url){setLoading(false);return}const start=Date.now(),timer=setInterval(()=>setElapsed(Math.floor((Date.now()-start)/1000)),500),controller=new AbortController(),limit=setTimeout(()=>controller.abort(),30000);fetch('/api/audit',{method:'POST',headers:{'content-type':'application/json'},body:JSON.stringify({url}),signal:controller.signal}).then(async r=>{const x=await r.json();if(!r.ok||x.error)throw Error(x.error||'Audit failed');setData(x);save({url:x.url,hostname:new URL(x.url).hostname,score:x.score,issues:x.issues.length,timestamp:new Date().toISOString(),title:x.title})}).catch(e=>setError(e.name==='AbortError'?'Audit exceeded 30 seconds. The website may be slow or blocking automated requests.':e.message)).finally(()=>{clearInterval(timer);clearTimeout(limit);setLoading(false)});return()=>{clearInterval(timer);clearTimeout(limit);controller.abort()}},[url]);
useEffect(()=>{if(!crawling)return;const t=setInterval(()=>setCrawlElapsed(v=>v+1),1000);return()=>clearInterval(t)},[crawling]);
async function runCrawl(){setError('');setCrawling(true);setCrawlElapsed(0);try{const r=await fetch('/api/crawl',{method:'POST',headers:{'content-type':'application/json'},body:JSON.stringify({url,maxPages:30})}),x=await r.json();if(!r.ok||x.error)throw Error(x.error);setCrawl(x);save({url,hostname:new URL(url).hostname,score:data?.score||0,issues:data?.issues.length||0,timestamp:new Date().toISOString(),title:data?.title||'',pages:x.stats.pagesCrawled})}catch(e){setError(e instanceof Error?e.message:'Crawl failed')}finally{setCrawling(false)}}
function saveReport(){if(!data)return;const a=document.createElement('a'),blob=new Blob([JSON.stringify({generatedAt:new Date().toISOString(),audit:data,crawl},null,2)],{type:'application/json'});a.href=URL.createObjectURL(blob);a.download=`sitelens-${new URL(data.url).hostname}.json`;a.click();URL.revokeObjectURL(a.href);setSaved(true);setTimeout(()=>setSaved(false),2000)}
const prior=useMemo(()=>data?history().filter((h:H)=>h.url===data.url)[1]:null,[data]);if(loading)return <Shell><div className="py-24"><div className="accent text-xs font-bold tracking-[.25em]">LIVE AUDIT</div><h1 className="text-4xl font-black mt-3">Auditing {url}…</h1><p className="muted mt-3">Collecting page evidence.</p><p className="muted text-sm mt-4">Elapsed: {elapsed}s · Typical completion: 5–15 seconds</p></div></Shell>;
if(error&&!data)return <Shell><h1 className="text-3xl font-bold">Audit couldn't complete</h1><p className="muted mt-3">{error}</p><div className="flex gap-3 mt-6"><button className="btn btn-primary" onClick={()=>location.reload()}>Try again</button><a className="btn btn-secondary" href="/">Audit another site</a></div></Shell>;if(!data)return null;
return <Shell><header className="flex flex-wrap justify-between gap-4"><div><div className="accent text-xs font-bold">AUDIT REPORT</div><button className="text-4xl font-black mt-2" onClick={()=>location.href='/'}>{new URL(data.url).hostname}</button><p className="muted mt-2">{data.title||'No title detected'}</p></div><div className="flex gap-2"><a className="btn btn-secondary" href="/">New audit</a><button className="btn btn-secondary" onClick={saveReport}>{saved?'Saved':'Save report'}</button><button className="btn btn-primary" onClick={runCrawl} disabled={crawling}>{crawling?`Crawling… ${crawlElapsed}s`:'Run full SEO crawl'}</button></div></header>{error&&<div className="card p-4 mt-5">{error}</div>}
<div className="grid lg:grid-cols-[180px_1fr] gap-6 mt-8"><div className="card p-5 flex flex-col items-center"><div className="score-ring" style={{'--score':`${data.score}%`} as React.CSSProperties}><div>{data.score}</div></div><b className="mt-3">Technical SEO</b></div><div className="grid sm:grid-cols-2 lg:grid-cols-4 gap-4"><Metric label="H1" value={data.h1s.length?`${data.h1s.length} detected`:'Missing'}/><Metric label="Meta description" value={data.description?'Present':'Missing'}/><Metric label="Schema" value={data.schemas.length?data.schemas.join(', '):'Not detected'}/><Metric label="Images / alt gaps" value={`${data.images} / ${data.imagesMissingAlt}`}/></div></div>
{prior&&<section className="card p-5 mt-6"><b>Historical change</b><div className="grid sm:grid-cols-2 gap-4 mt-3"><Delta label="SEO score" now={data.score} old={prior.score}/><Delta label="Issues" now={data.issues.length} old={prior.issues} inverse/></div></section>}
{crawl&&<><section className="grid sm:grid-cols-2 lg:grid-cols-4 gap-4 mt-8"><Stat label="Pages crawled" v={crawl.stats.pagesCrawled}/><Stat label="Errors" v={crawl.stats.errors}/><Stat label="Not indexable" v={crawl.stats.notIndexable}/><Stat label="Missing titles" v={crawl.stats.missingTitles}/></section><section className="card p-6 mt-8"><h2 className="text-xl font-bold">SEO intelligence findings</h2><p className="muted text-sm mt-1">Robots: {crawl.robotsFound?'found':'not found'} · Sitemap: {crawl.sitemapFound?'found':'not found'}</p><div className="space-y-3 mt-5">{crawl.findings.map((f,i)=><div key={i} className="border border-[#353133] rounded-xl p-4"><span className="pill">{f.severity.toUpperCase()}</span> <b className="ml-2">{f.title}</b><p className="muted text-sm mt-2"><b>Evidence:</b> {f.evidence}</p><p className="text-sm mt-2"><b>Fix:</b> {f.fix}</p></div>)}</div></section></>}
</Shell>}
function Shell({children}:{children:React.ReactNode}){return <main className="min-h-screen grid-bg"><div className="max-w-6xl mx-auto px-6 py-8"><div className="font-black text-xl">Site<span className="accent">Lens</span></div>{children}</div></main>}function Metric({label,value}:{label:string,value:string}){return <div className="card p-5"><div className="muted text-xs">{label}</div><b className="mt-2 block">{value}</b></div>}function Stat({label,v}:{label:string,v:number}){return <div className="card p-5"><div className="muted text-xs">{label}</div><b className="text-3xl block mt-2">{v}</b></div>}function Delta({label,now,old,inverse}:{label:string,now:number,old:number,inverse?:boolean}){const d=now-old;return <div><div className="muted text-xs">{label}</div><b className="text-2xl">{now}</b><span className="muted ml-2">{d>0?'+':''}{d}{inverse?' (lower is better)':''}</span></div>}
